language: ruby
rvm:
  - 1.9.3
before_script:
  - mysql -e 'create database eerlijkepolitiek_test;'
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=cucumber bundle exec rake db:test:prepare
